### ISSUE TITLE
postbox ?

### ISSUE THREAD

**Issue by Tecktorious** [scalefog/scf_telegram#1]
wheres the postbox ? should i creaone one collum myself ?

**Comment by actstorms** [comment]
Hi, I have forgot to add this to the mysql file. Yes, you have to add postbox collum to your characters table.  varchar(6)

**Comment by Tecktorious** [comment]
the problem is what the postbox will have in it ??

**Comment by actstorms** [comment]
I have added the missing string in db.sql file.  This script will auto generate a postbox code if the character not have it.

**Comment by outsider31000** [comment]
blips ain't working, also can't write first and last name, only first name.  and everything is in caps.  tried to send it to me and there's no telegram. also in the DB  it doesn't say who sent it. only a weird number that only the person knows.

**Comment by actstorms** [comment]
Postbox number is required.  Like phone numbers, Maybe it will be developed more in the futures.
